CREATE USER c##db_esse4 IDENTIFIED BY dbes;
CREATE USER c##docente IDENTIFIED BY doce;
CREATE USER c##studente IDENTIFIED BY stud;
CREATE USER c##segreteria IDENTIFIED BY segr;

GRANT ALL PRIVILEGES TO c##db_esse4;

GRANT CREATE ANY VIEW TO c##db_esse4;
GRANT CREATE ANY VIEW TO c##segreteria;

GRANT CREATE ANY PROCEDURE TO c##db_esse4;
GRANT CREATE ANY PROCEDURE TO c##segreteria;