GRANT CONNECT, CREATE SESSION TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON corso_laurea TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON studente TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON docente TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON insegnamento TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON edizione_insegnamento TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON offerta_insegnamento TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON insegna_edizione TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON frequenta_edizione_insegnamento TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON appello_laurea TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON prenotazione_appello_seduta TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON partecipa_seduta TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON seduta_laurea TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON relatore TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON azienda TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON tutor_aziendale TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON tirocinio TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON questionario TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON appello TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON orario_lezioni TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON seminario TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON presiede_appello TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON ricevimento TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON esame_superato TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON prenotazione_ricevimento TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON prenotazione_appello TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON tassa TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON partecipa_seminario TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON bando_borsa TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON bando_erasmus TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON partecipazione_bando_borsa TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON partecipazione_bando_erasmus TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON assegnazione_borse TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON assegnazione_erasmus TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON telefono_studente TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON email_studente TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON telefono_tutor_aziendale TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON email_tutor_aziendale TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON telefono_docente TO c##segreteria;
GRANT SELECT, INSERT, UPDATE, DELETE ON email_docente TO c##segreteria;

GRANT SELECT  ON vista_corsi_di_laurea_posti_disponibili TO c##segreteria;
GRANT SELECT ON vista_seminari_prossimo_mese TO c##segreteria;
GRANT SELECT ON vista_bando_borsa_studio TO c##segreteria;
GRANT SELECT ON vista_bando_erasmus TO c##segreteria;

GRANT EXECUTE ON procedura_programmazione_appelli TO c##segreteria;
GRANT EXECUTE ON procedura_calcola_statistiche_esami_e_laurea TO c##segreteria;
GRANT EXECUTE ON procedura_assegnazione_tutor_tirocinio TO c##segreteria;
GRANT EXECUTE ON procedura_assegnazione_tutor_docente_tirocinio_interno TO c##segreteria;
GRANT EXECUTE ON procedura_inserimento_insegnamento TO c##segreteria;
GRANT EXECUTE ON procedura_assegnazione_docente_insegna_edizione TO c##segreteria;